### ISSUE TITLE
Product Name - correct from templated value

### ISSUE THREAD

**Issue by momiller121** [momiller121/westjet-weather#4]
The hapi-path project refers to 'AwesomeProduct' as the class name for the product. This should be correct to something more suitable for this API project.

**Comment by Basharfrancis** [comment]
Ok, I will change it

**Comment by momiller121** [comment]
Looking at it in context, the value needs to be a suitable variable name. Something short like "WestJetWeather" or "AirportWeatherAPI" would be preferable.

**Comment by Basharfrancis** [comment]
I would go with AirportWeather Api
